export const HEARTBEAT_RESOLUTION_MS = 20;
export const GC_CORRELATION_LOOKAROUND_MS = 20;
export const EVENT_LOOP_STALL_INTERVAL_MS = 200;

export const INSPECTOR_STARTUP_TIMEOUT_MS = 5_000;
export const TERMINATE_GRACE_MS = 500;
export const TERMINATE_SIGTERM_WAIT_MS = 2_000;
export const TERMINATE_SIGKILL_FALLBACK_MS = 1_000;

export const DEFAULT_SAMPLE_INTERVAL_MICROS = 1000;
export const MIN_SAMPLE_INTERVAL_MICROS = 50;
