#!/usr/bin/env node
import { readFile, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = resolve(__dirname, '..');
const packageJsonPath = resolve(root, 'package.json');
const outputPath = resolve(root, 'src', 'report', 'version.generated.ts');

const packageJson = JSON.parse(await readFile(packageJsonPath, 'utf8'));

const version = typeof packageJson.version === 'string' ? packageJson.version : '0.0.0';
const source = `// Generated by scripts/generate-version.js
export const LANTERNA_VERSION = ${JSON.stringify(version)} as const;
`;

await writeFile(outputPath, source, 'utf8');
